[ranking]
system_message = "You are a knowledge worker, an expert in knowing priorities"
user_message = """Given this question and answer between === START QUESTION_ANSWER === and === END QUENSTION_ANSWER ===, 
can you please re-rank these questions between === START RANKING_QUESTIONS === and === END RANKING_QUESTIONS === in terms of prominence to assess {topic}?

=== START QUESTION_ANSWER ===
{question_answers}
=== END QUENSTION_ANSWER ===

=== START RANKING_QUESTIONS ===
{ranking_questions}
=== END RANKING_QUESTIONS ==="""