[ranking]
system_message = "You are a knowledge worker, an expert in knowing priorities"
user_message = """Given these questions and answers between === START QUESTION_ANSWER === and === END QUESTION_ANSWER ===, 
can you please re-rank the questions (from most relevant to most irrelevant) you can find between === START RANKING_QUESTIONS === and === END RANKING_QUESTIONS === in terms of prominence to assess this topic: "{topic}"?

=== START QUESTION_ANSWER ===
{question_answers}
=== END QUESTION_ANSWER ===

=== START RANKING_QUESTIONS ===
{ranking_questions}
=== END RANKING_QUESTIONS ==="""

[ranking.together]
user_message = """Given these questions and answers between === START QUESTION_ANSWER === and === END QUENSTION_ANSWER ===, 
can you please re-rank the questions (from most relevant to most irrelevant) you can find between === START RANKING_QUESTIONS === and === END RANKING_QUESTIONS === in terms of prominence to assess this topic: {topic}?

=== START QUESTION_ANSWER ===
{question_answers}
=== END QUENSTION_ANSWER ===

=== START RANKING_QUESTIONS ===
{ranking_questions}
=== END RANKING_QUESTIONS ===

The model will then use the provided answers to the questions to generate a ranked list of questions that are most relevant to the topic of {topic}. The ranked list will be provided in the output of the model.
Please respond using a JSON list with the topics like this one:
```json
[
"Is there market demand for the type of data your organization possess?",
"Is there a need or opportunity to simplify data sharing and collaboration amoungst internal teams?"
]
```
"""

[ranking.topics]
system_message = "You are a knowledge worker, an expert in knowing priorities"
user_message = """Given these questions and answers between === START QUESTION_ANSWER === and === END QUENSTION_ANSWER ===, 
can you please re-rank the topics (from most relevant to most irrelevant) you can find between === START RANKING_TOPICS === and === END RANKING_TOPICS ===?

=== START QUESTION_ANSWER ===
{question_answers}
=== END QUENSTION_ANSWER ===

=== START RANKING_TOPICS ===
{ranking_topics}
=== END RANKING_TOPICS ==="""

[sentiment]
system_message = "You are an expert in terms of determining the sentiment or emotion expressed in a piece of text."
user_message = """Classify the sentiment of the following question given a specific question. 
The question can be found between === START QUESTION === and === END QUESTION === and the answer can be found between === START ANSWER === and === END ANSWER ===

=== START QUESTION ===
{question}
=== END QUESTION ===

=== START ANSWER ===
{answer}
=== END ANSWER ==="""

[answer-quality]
system_message = "You are a helpful assistant"
user_message = """Determine whether the answer to the question in topic `{topic}` mentioned below is adequate or not. The question and topic are mentioned below.

```
Question: {question}
Answer: {answer}
```
"""


[suggestion.yes_no]
system_message = "You are a helpful assistant who gives suggestions in British English"
user_message = """Give a list of possible answers for the question related to the topic "{topic}" that can be found between === START QUESTION === and === END QUESTION ===.
You do not need to give factual answers, just some possible answers to this question. If the answer is affirmative use a simple "Yes" or negative a simple "No" as the text answer.

Here are some examples on how to respond to a question:

Question: Is there comprehensive documentation of data governance policies, procedures, and standards??
No Answer: No, we have not started yet.
Yes Answer: Yes, definitely, of course
Maybe Answer: Partially, some, only some of them

Question: What are the organization's overall business goals and objectives?
No Answer: This is a confidential matter. We would prefer not to disclose these details.
Yes Answer: The main goals are profit maximization - we want to increase the overall profit of the organization and market share growth, i.e. expand the organization's share of the market.
Maybe Answer: Improving customer satisfaction is one of them, however I need to get myself a better picture about the overall business goals.

Please use the following titles:

Affirmative, Negative and Undecided

=== START QUESTION ===
{question}
=== END QUESTION ===

Please generate only 3 answers at most.

"""

[suggestion.open_ended]
system_message = "You are a helpful assistant who gives suggestions in British English"
user_message = """Give a list of possible answers for the question related to the topic "{topic}" that can be found between === START QUESTION === and === END QUESTION ===.
You do not need to give factual answers, just some possible answers to this question.

Here are some examples on how to respond to a question:

Question: What are the organization's overall business goals and objectives?
Answer 1: Increase revenue and turn-over
Answer 2: Improve our working culture and promote life style balance
Answer 3: Modernize our company, moving away from traditional manufacturing methods to new methods with improved automation

Please use appropriate titles for each response.

=== START QUESTION ===
{question}
=== END QUESTION ===

Please generate only 3 answers at most.

"""

[suggestion_proximity]
system_message = "You are a helpful assistant"
user_message = """Given the following answer between === START ANSWER === and === END ANSWER ===, can you please find the most related suggestion which you can find between === START SUGGESTIONS === and === END SUGGESTIONS === ?

=== START ANSWER ===
{answer}
=== END ANSWER ===

=== START SUGGESTIONS ===
{suggestions}
=== END SUGGESTIONS ===
"""
